# Generated by Django 5.0.4 on 2024-04-24 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget_Data',
            fields=[
                ('gadget_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
                ('product_url', models.TextField()),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('InStock', models.BooleanField()),
                ('LastUpdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.TextField()),
                ('rating', models.SmallIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Gadget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.gadget_data')),
            ],
        ),
        migrations.CreateModel(
            name='Gadget_keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Keyword', models.CharField(max_length=60)),
                ('Gadget_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.gadget_data')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Website_Source',
            fields=[
                ('web_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('url', models.URLField()),
                ('GadgetID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.gadget_data')),
            ],
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.TimeField()),
                ('closing_time', models.TimeField()),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.location')),
                ('web_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BaseApp.website_source')),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('list_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
